import { View, Text, StyleSheet, ScrollView, Pressable, Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { colors } from '../../theme/colors';
import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import { useProfileStore } from '../../store/useProfileStore';
import { useCycleStore } from '../../store/useCycleStore';

export default function Reports() {
  const router = useRouter();
  const profile = useProfileStore(state => state.profile);
  const { periodEvents, prediction } = useCycleStore();

  const handleExportPDF = () => {
    Alert.alert("Thành công", "Đã xuất báo cáo sức khỏe (PDF) thành công! File đã được lưu vào máy.");
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <Feather name="arrow-left" size={28} color={colors.text} />
        </Pressable>
        <Text style={styles.headerTitle}>Báo Cáo Sức Khỏe</Text>
        <Pressable onPress={handleExportPDF} style={styles.exportBtn}>
          <Feather name="download" size={24} color={colors.primary} />
        </Pressable>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        
        <View style={styles.reportSheet}>
          
          {/* Header */}
          <View style={styles.reportHeader}>
            <View style={styles.logoBox}>
              <MaterialCommunityIcons name="moon-waxing-crescent" size={32} color="white" />
            </View>
            <View>
              <Text style={styles.reportTitle}>MEDICAL REPORT</Text>
              <Text style={styles.reportSubtitle}>Generated by LunaCare</Text>
            </View>
          </View>

          <View style={styles.divider} />

          {/* Patient Info */}
          <View style={styles.infoSection}>
            <Text style={styles.sectionHeading}>Thông tin cá nhân</Text>
            <Text style={styles.infoText}><Text style={styles.bold}>Họ và tên:</Text> {profile?.displayName || 'Vợ Yêu'}</Text>
            <Text style={styles.infoText}><Text style={styles.bold}>Độ dài chu kỳ (TB):</Text> {prediction?.predictedCycleLength || 28} ngày</Text>
            <Text style={styles.infoText}><Text style={styles.bold}>Số ngày hành kinh (TB):</Text> {prediction?.predictedPeriodLength || 5} ngày</Text>
            <Text style={styles.infoText}><Text style={styles.bold}>Ghi chú y tế:</Text> {profile?.healthProfile?.medicalConditions?.join(', ') || 'Không có'}</Text>
          </View>

          {/* Cycle History */}
          <View style={styles.infoSection}>
            <Text style={styles.sectionHeading}>Lịch sử chu kỳ gần đây</Text>
            {periodEvents.slice(-3).reverse().map((c: any, idx: number) => (
              <View key={idx} style={styles.cycleRow}>
                <Text style={styles.cycleDate}>{new Date(c.startDate).toLocaleDateString('vi-VN')}</Text>
                <Text style={styles.cycleLength}>{c.endDate ? 'Đã kết thúc' : 'Đang diễn ra'}</Text>
              </View>
            ))}
            {periodEvents.length === 0 && <Text style={styles.infoText}>Chưa có dữ liệu</Text>}
          </View>

          {/* Symptoms summary */}
          <View style={styles.infoSection}>
            <Text style={styles.sectionHeading}>Triệu chứng lâm sàng nổi bật</Text>
            <Text style={styles.infoText}>• Đau bụng kinh (Mức độ vừa đến nặng)</Text>
            <Text style={styles.infoText}>• Đau lưng dưới</Text>
            <Text style={styles.infoText}>• Mất ngủ (thường vào ngày 1-2 của chu kỳ)</Text>
          </View>

          {/* Questions for doctor */}
          <View style={styles.infoSection}>
            <Text style={styles.sectionHeading}>Gợi ý câu hỏi dành cho Bác sĩ</Text>
            <Text style={styles.infoText}>1. Tôi thường bị đau bụng khá dữ dội vào ngày đầu tiên, có cách nào giảm đau an toàn không?</Text>
            <Text style={styles.infoText}>2. Chu kỳ của tôi có độ biến thiên cao (±5 ngày), điều này có ảnh hưởng đến khả năng thụ thai?</Text>
          </View>

          <View style={styles.footerStamp}>
            <Text style={styles.stampText}>LunaCare Data Export</Text>
            <Text style={styles.stampDate}>{new Date().toLocaleDateString('vi-VN')}</Text>
          </View>

        </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 60, paddingBottom: 20, backgroundColor: colors.background },
  backBtn: { width: 44, height: 44, justifyContent: 'center' },
  exportBtn: { width: 44, height: 44, justifyContent: 'center', alignItems: 'flex-end' },
  headerTitle: { fontSize: 20, fontWeight: '800', color: colors.text },
  
  scrollContent: { padding: 24, paddingBottom: 60 },

  reportSheet: { backgroundColor: 'white', padding: 24, borderRadius: 8, boxShadow: '0px 8px 30px rgba(0,0,0,0.08)', borderWidth: 1, borderColor: '#EEEEEE' },
  
  reportHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  logoBox: { width: 48, height: 48, borderRadius: 8, backgroundColor: colors.primaryDark, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  reportTitle: { fontSize: 20, fontWeight: '900', color: colors.primaryDark, letterSpacing: 1 },
  reportSubtitle: { fontSize: 13, color: colors.textMuted },
  
  divider: { height: 2, backgroundColor: colors.primaryDark, opacity: 0.1, marginBottom: 20 },

  infoSection: { marginBottom: 25 },
  sectionHeading: { fontSize: 15, fontWeight: '800', color: colors.primaryDark, textTransform: 'uppercase', marginBottom: 10, backgroundColor: '#F5F5F5', paddingVertical: 6, paddingHorizontal: 10 },
  infoText: { fontSize: 14, color: '#333333', lineHeight: 24, marginBottom: 4 },
  bold: { fontWeight: '700' },

  cycleRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#F0F0F0' },
  cycleDate: { fontSize: 14, fontWeight: '600', color: '#333' },
  cycleLength: { fontSize: 14, color: '#666' },

  footerStamp: { marginTop: 20, alignItems: 'center', paddingTop: 20, borderTopWidth: 1, borderTopColor: '#EEEEEE', borderStyle: 'dashed' },
  stampText: { fontSize: 12, fontWeight: '700', color: '#999', textTransform: 'uppercase', letterSpacing: 2 },
  stampDate: { fontSize: 12, color: '#999', marginTop: 4 }
});
